common: &common
  adapter: postgresql
  username:
  password:

development:
  <<: *common
  database: all_your_base_development

test:
  <<: *common
  database: all_your_base_test

production:
  <<: *common
  database: all_your_base_production